# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf45421941965939af06a86ffc450237b06c7880ca2ee75493bb6bedcd4771f64d74e1f70b7b1f9786834e158da7868d13ff8c481fc63a97a3d66e5619e52230

test:
  secret_key_base: c039ee21906b7e45a891d68ab9d5ccf9c21aac98ed5bd3f55ac0f87e4d2adc0350d788e603c0074cddc647a9ad511bf9c94a3b73b2fafd53b1b9c923931fc68c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
